# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'addME.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 134)
        Dialog.setStyleSheet("background-color: rgb(222, 222, 222);")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(10, 30, 211, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.lEdit_Medicamento = QtWidgets.QLineEdit(Dialog)
        self.lEdit_Medicamento.setGeometry(QtCore.QRect(220, 30, 141, 20))
        self.lEdit_Medicamento.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lEdit_Medicamento.setFont(font)
        self.lEdit_Medicamento.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lEdit_Medicamento.setObjectName("lEdit_Medicamento")
        self.btn_aggMedicament = QtWidgets.QPushButton(Dialog)
        self.btn_aggMedicament.setGeometry(QtCore.QRect(50, 90, 101, 31))
        self.btn_aggMedicament.setObjectName("btn_aggMedicament")
        self.btn_cerrar = QtWidgets.QPushButton(Dialog)
        self.btn_cerrar.setGeometry(QtCore.QRect(230, 70, 101, 31))
        self.btn_cerrar.setObjectName("btn_cerrar")
        self.lbl_medAggSucces = QtWidgets.QLabel(Dialog)
        self.lbl_medAggSucces.setGeometry(QtCore.QRect(80, 110, 261, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lbl_medAggSucces.setFont(font)
        self.lbl_medAggSucces.setText("")
        self.lbl_medAggSucces.setObjectName("lbl_medAggSucces")
        self.lineEdit = QtWidgets.QLineEdit(Dialog)
        self.lineEdit.setGeometry(QtCore.QRect(90, 50, 113, 20))
        self.lineEdit.setObjectName("lineEdit")

        self.retranslateUi(Dialog)
        self.btn_cerrar.clicked.connect(Dialog.close) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Agregar medicamento"))
        self.label.setText(_translate("Dialog", "Nombre del medicamento"))
        self.btn_aggMedicament.setText(_translate("Dialog", "Agregar"))
        self.btn_cerrar.setText(_translate("Dialog", "Cerrar"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
